### ISSUE TITLE
Move passive expiration logic to DB Class

### ISSUE THREAD

**Issue by tuhuynh27** [keva-dev/keva#57]
`ExpirationManager` should be placed in DB Classes, each time use `get`, if will check and trigger expiration logic.

**Comment by the123saurav** [comment]
Hi @tuhuynh27, I was just checking out this issue.
May I know why this is a bug? Or is it just refactoring?

**Comment by axblueblader** [comment]
Hi @the123saurav , for context the issue is: we will have a lot of code duplication, cause every 'key' level command will need expiration logic.

However there's also this problem
when trigger expiration in upper level, it can be considered a command -> all the replication/persistence logic can be applied ex: when expiration happens, a DEL command can be replicate to others or write to aof
when done in DB level, it's internal to DB and the node instance, no replication/persistence logic can be apply and DB shouldn't have any other dependencies anyways.

So far I got no simple solution yet besides using AOP, reflections stuff to inject code for every key level command
